# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(rhino)
library(shiny)
library(bslib)
library(tidyr)
library(shiny.router)

# sk dependencies
library(box)
library(rlang)
library(purrr)
library(fst)
library(cli)
library(magrittr)
library(stringr)
library(dplyr)
library(tibble)
library(palettes)
library(ggplot2)
library(scales)
library(lubridate)
library(readxl)

# srqlib dependencies
library(fst)
library(stringr)
library(dplyr)
library(purrr)
library(lubridate)
library(cli)
library(ggplot2)
library(palettes)
library(scales)
library(tidyr)
library(tidyselect)
library(sysfonts)
library(showtext)
library(forcats)
library(rlang)
library(knitr)
library(kableExtra)
